### ISSUE TITLE
starfind adds structures to the input image

### ISSUE THREAD

**Issue by Wagner25** [sparc4-dev/astropop#115]
Com a nova versão do astropop, onde usamos global_bkg=True no cálculo do background, parece que o starfind adiciona quadrados nas posições das fontes encontradas na imagem de entrada.
Além disso, como uso o starfind duas vezes no notebook (uma para a astrometria e outra para a fotometria de abertura) é necessário recriar a imagem de entrada no momento da segunda aplicação do starfind, pois se isso não for feito, é encontrado menos fontes. Por exemplo, numa imagem recriando a imagem de entrada obtenho 472 fontes, enquanto sem recriar obtenho apenas 34 fontes (possivelmentes com valores incorretos de fluxo).

**Comment by juliotux** [comment]
Please, confirm if it is fixes in v0.9.2
