### ISSUE TITLE
Starfind and Aperture Photometry

### ISSUE THREAD

**Issue by FisiCarol** [sparc4-dev/astropop#116]
Como dito no issue #115, quadrados são adicionados, então, em alguns casos, não consigo ter certeza se existe fonte pontual. Vou mandar as figuras por e-mail.

De toda forma, talvez esteja acontecendo algo na fotometria de abertura também, por exemplo, para o filtro r, foram achados 15 pares e temos 161 imagens. A fotometria de abertura já está demorando mais que 1h:30min

**Comment by juliotux** [comment]
Please, confirm if it is fixes in v0.9.2
