### ISSUE TITLE
"estimate_dxdy" parameters documentation

### ISSUE THREAD

**Issue by FFalkenbergM** [sparc4-dev/astropop#65]
Couldn't find the description for the parameters of the "estimate_dxdy" function.

https://astropop.readthedocs.io/en/latest/_api/astropop.polarimetry.dualbeam.estimate_dxdy.html?highlight=estimate_DXDY#astropop.polarimetry.dualbeam.estimate_dxdy

**Comment by juliotux** [comment]
fixed by 879db6307192711918c78676f420bd9a0d23c5a5
