### ISSUE TITLE
Include an estimate of the theoretical polarization error 

### ISSUE THREAD

**Issue by claudiavr** [sparc4-dev/astropop#72]
Sugiro utilizarmos a expressao do erro teorico da polarizacao do link abaixo. Ela inclui o ruido de Poisson das contagens da fonte e ceu, ruido de leitura e ganho. Essa expressao deve ser adaptada para uso em medidas do seguinte modo:

    N* t_exp: valor medio das contagens somando os feixes ordinario e extraordinario por posicao da lamina
    N_s* t_exp: valor medio das contagens do ceu por pixel por posicao da lamina  (sugiro usarmos o valor medio do ceu ord. e extraord.)

http://www.inpe.br/etc/docs/calculo_erro_polarizacao.pdf

**Comment by juliotux** [comment]
@claudiavr , please check if this equation is ok:

$SNR_{sum} = \sqrt{\frac{\sum Z_i}{\sum\sigma_{Z_i}}}$

$\sigma_{theor} = 100\\% \cdot K\cdot \frac{1}{SNR_{sum}}$

**Comment by juliotux** [comment]
@claudiavr , please check if this equation is correct.

$SNR_{total} = \sqrt{\sum{(\frac{Zi}{\sigma_{Zi}})^2}}$
$\sigma_{theor} = 100\\% \cdot K \cdot \frac{1}{SNR_{total}}$

In principle, I think the $Zi$ terms carry the photometry SNR and, summing $N_{WP}$ terms with same SNR we get $SNR_{total} = \sqrt{N_{WP}} \cdot SNR$.

**Comment by claudiavr** [comment]
The sigma_theor expression seems correct for me.

The sum expression for the SNR_total is correct, but I think the "i" parcels are not correct, if Z_i = (f_ord - f_ext)/(f_ord + f_ext), where:

f_ord is the flux of the ordinary beam (already subtracted from the sky) in the "i" image;
f_ext is the flux of the extraordinary beam (already subtracted from the sky)  in the "i" image.

Each parcel should be:

parcel_i = (f_ord + f_ext)/{f_ord + f_ext+ 2* npix[f_sky + B * N_R^2 + (0.289* G)^2]},

where

f_sky is the sky counts per pixel in the "i" image.

**Comment by juliotux** [comment]
Reopening to fix the expression.
