### ISSUE TITLE
Couldn't find the rms value in the Stokes Parameters

### ISSUE THREAD

**Issue by FFalkenbergM** [sparc4-dev/astropop#73]
The output of the SLSDualBeamPolarimetry.compute doesn't provide the rms value.
For example (snorm is my variable containing the Stokes Parameters): 

snorm.rms

---------------------------------------------------------------------------
UnitConversionError                       Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/astropy/units/quantity_helper/helpers.py in get_converters_and_unit(f, unit1, unit2)
     67         try:
---> 68             converters[changeable] = get_converter(unit2, unit1)
     69         except UnitsError:

~/.local/lib/python3.8/site-packages/astropy/units/quantity_helper/helpers.py in get_converter(from_unit, to_unit)
     31     i.e., if the inferred scale is unity."""
---> 32     converter = from_unit._get_converter(to_unit)
     33     return None if converter is unit_scale_converter else converter

~/.local/lib/python3.8/site-packages/astropy/units/core.py in _get_converter(self, other, equivalencies)
   1060 
-> 1061             raise exc
   1062 

~/.local/lib/python3.8/site-packages/astropy/units/core.py in _get_converter(self, other, equivalencies)
   1045         try:
-> 1046             return self._apply_equivalencies(
   1047                 self, other, self._normalize_equivalencies(equivalencies))

~/.local/lib/python3.8/site-packages/astropy/units/core.py in _apply_equivalencies(self, unit, other, equivalencies)
   1021 
-> 1022         raise UnitConversionError(
   1023             f"{unit_str} and {other_str} are not convertible")

UnitConversionError: '' (dimensionless) and 'rad' (angle) are not convertible

During handling of the above exception, another exception occurred:

UnitConversionError                       Traceback (most recent call last)
<ipython-input-99-ce8edb92323e> in <module>
----> 1 snorm.rms

~/.local/lib/python3.8/site-packages/astropop/polarimetry/dualbeam.py in rms(self)
    231             model = partial(halfwave_model, q=self.q, u=self.u, zero=self.zero)
    232 
--> 233         return np.std(self.zi-model(self.psi))
    234 
    235 

~/.local/lib/python3.8/site-packages/astropop/polarimetry/dualbeam.py in quarterwave_model(psi, q, u, v, zero)
    145     if zero is not None:
    146         psi = psi+zero  # avoid inplace modification
--> 147     psi = np.radians(psi)
    148     psi2 = 2*psi
    149     zi = q*(np.cos(psi2)**2) + u*np.sin(psi2)*np.cos(psi2) - v*np.sin(psi2)

~/.local/lib/python3.8/site-packages/astropop/math/physical.py in __array_ufunc__(self, ufunc, method, *inputs, **kwargs)
    479             raise NotImplementedError("`out` argument not supported yet.")
    480 
--> 481         result = HANDLED_UFUNCS[ufunc](*inputs, **kwargs)
    482 
    483         return result

~/.local/lib/python3.8/site-packages/astropop/math/physical.py in _qfloat_radians(qf, *args, **kwargs)
    895 def _qfloat_radians(qf, *args, **kwargs):
    896     """Convert any qfloat angle to radian."""
--> 897     return qf.to(units.radian)
    898 
    899 

~/.local/lib/python3.8/site-packages/astropop/math/physical.py in to(self, unit)
    396         """
    397         other = units.Unit(unit, parse_strict='silent')
--> 398         (_, conv), unit = get_converters_and_unit(self.to, other, self.unit)
    399         if conv is not None:
    400             nvalue = conv(self.nominal)

~/.local/lib/python3.8/site-packages/astropy/units/quantity_helper/helpers.py in get_converters_and_unit(f, unit1, unit2)
     68             converters[changeable] = get_converter(unit2, unit1)
     69         except UnitsError:
---> 70             raise UnitConversionError(
     71                 "Can only apply '{}' function to quantities "
     72                 "with compatible dimensions"

UnitConversionError: Can only apply 'to' function to quantities with compatible dimensions

**Comment by juliotux** [comment]
Please, print the `snorm` dict

```
print(snorm.__dict__)
```
