### ISSUE TITLE
Gaia limited to 2000 sources

### ISSUE THREAD

**Issue by juliotux** [sparc4-dev/astropop#94]
Gaia DR3 queries limit results to 2000 sources, even with `ROW_LIMIT=-1` set. This behavior is not seen when use direct query with astroquery.

```
In [15]: g = gaia.GaiaDR3SourcesCatalog('RMC 40', radius='15 arcmin')

In [16]: len(g)
Out[16]: 2000
```

**Comment by claudiavr** [comment]
Seria legal ter tb um limite de mag máxima.
